version: "3.8"

services:
  devices-registry:
    build: .
    container_name: devices-registry-app
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - mlops_network

networks:
  mlops_network:
