spring:
    application:
        name : devicesRegistry

    datasource:
        url: jdbc:postgresql://db.gedbzyncroztaynopauh.supabase.co:5432/postgres?sslmode=require
        username: postgres
        password: Asdfghjkl!@#123
        driver-class-name: org.postgresql.Driver


    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

server:
    port : 8180
