spring:
    application:
        name : devicesRegistry

    datasource:
        url: jdbc:postgresql://c-mlopsdvregistrydb.jpvkychhvethk3.postgres.cosmos.azure.com:5432/dvregistry_db?sslmode=require
        username: citus
        password: asdfghjkl!@#123
        driver-class-name: org.postgresql.Driver


    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

server:
    port : 8180
