spring:
    application:
        name : devicesRegistry

    datasource:
        url: jdbc:postgresql://c-devices-registry-db.p2agjllch2owbp.postgres.cosmos.azure.com:5432/citus?sslmode=require
        username: citus
        password: Asdfghjkl!@#123
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 2
            idle-timeout: 600000           
            max-lifetime: 1800000          
            keepalive-time: 300000         


    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

server:
    port : 8180
